@echo off
Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
call .\AiTOMM\Scripts\activate.bat
python ImageGenarator.py Diagram_illustrating_various_aspects_of_memory,_including_types_such_as_procedural,_episodic,_semantic,_and_working_memory,_as_well_as_factors_influencing_memory_like_conditioning_and_emotion.
pause
